// Options the user could type in
const prompts = [
    ["hi", "hey", "hello", "good morning", "good afternoon"],
    ["how are you", "how is life", "how are things"],
    ["what are you doing", "what is going on", "what is up"],
    ["how old are you"],
    ["who are you", "are you human", "are you bot", "are you human or bot"],
    ["who created you", "who made you"],
    [
      "your name please",
      "your name",
      "may i know your name",
      "what is your name",
      "what call yourself"
    ],
    ["i love you"],
    ["happy", "good", "fun", "wonderful", "fantastic", "cool"],
    ["bad", "bored", "tired"],
    ["help me", "tell me story", "tell me joke"],
    ["ah", "yes", "ok", "okay", "nice"],
    ["bye", "good bye", "goodbye", "see you later"],
    ["what should i eat today"],
    ["bro"],
    ["what", "why", "how", "where", "when"],
    ["no","not sure","maybe","no thanks"],
    [""],
    ["haha","ha","lol","hehe","funny","joke"],
    [
      "book category",
      "book categories",
      "website book category",
      "website book categories",
      "library book category",
      "library book categories",
      "recommend book category",
      "recommend book categories",
      "recommend website book category",
      "recommend webiste book categories",
      "recommend library book category",
      "recommend library book categories",
      "book category recommend",
      "book categories recommend",
      "website book category recommend",
      "website book categories recommend",
      "library book category recommend",
      "library book categories recommend"
    ],
    [
      "book",
      "books",
      "website book",
      "website books",
      "library book",
      "library books",
      "recommend book",
      "recommend books",
      "recommend website book",
      "recommend webiste books",
      "recommend library book",
      "recommend library books",
      "book recommend",
      "books recommend",
      "website book recommend",
      "website books recommend",
      "library book recommend",
      "library books recommend"
    ],
    [
      "laptop",
      "laptops",
      "website laptop",
      "website laptops",
      "library laptop",
      "library laptops",
      "recommend laptop",
      "recommend laptops",
      "recommend website laptop",
      "recommend webiste laptops",
      "recommend library laptop",
      "recommend library laptops",
      "laptop recommend",
      "laptops recommend",
      "website laptop recommend",
      "website laptops recommend",
      "library laptop recommend",
      "library laptops recommend"
    ],
    [
      "student study room",
      "student study rooms",
      "website student study room",
      "website student study rooms",
      "library student study room",
      "library student study rooms",
      "recommend student study room",
      "recommend student study rooms",
      "recommend website student study room",
      "recommend webiste student study rooms",
      "recommend library student study room",
      "recommend library student study rooms",
      "student study room recommend",
      "student study rooms recommend",
      "website student study room recommend",
      "website student study rooms recommend",
      "library student study room recommend",
      "library student study rooms recommend"
    ],
    [
      "teacher study room",
      "teacher study rooms",
      "website teacher study room",
      "website teacher study rooms",
      "library teacher study room",
      "library teacher study rooms",
      "recommend teacher study room",
      "recommend teacher study rooms",
      "recommend website teacher study room",
      "recommend webiste teacher study rooms",
      "recommend library teacher study room",
      "recommend library teacher study rooms",
      "teacher study room recommend",
      "teacher study rooms recommend",
      "website teacher study room recommend",
      "website teacher study rooms recommend",
      "library teacher study room recommend",
      "library teacher study rooms recommend"
    ],
    [
      "outsider study room",
      "outsider study rooms",
      "website outsider study room",
      "website outsider study rooms",
      "library outsider study room",
      "library outsider study rooms",
      "recommend outsider study room",
      "recommend outsider study rooms",
      "recommend website outsider study room",
      "recommend webiste outsider study rooms",
      "recommend library outsider study room",
      "recommend library outsider study rooms",
      "outsider study room recommend",
      "outsider study rooms recommend",
      "website outsider study room recommend",
      "website outsider study rooms recommend",
      "library outsider study room recommend",
      "library outsider study rooms recommend"
    ],
    [
      "view book",
      "view books",
      "view library book",
      "view library books",
      "view website book",
      "view website books",
      "how to view book",
      "how to view books",
      "how to view library book",
      "how to view library books",
      "how to view website book",
      "how to view website books",
      "book viewing guidance",
      "books viewing guidance",
      "library book viewing guidance",
      "library books viewing guidance",
      "website book viewing guidance",
      "website books viewing guidance"
    ],
    [
      "view book detail",
      "view book details",
      "view library book detail",
      "view library book details",
      "view website book detail",
      "view website book details",
      "how to view book detail",
      "how to view book details",
      "how to view library book detail",
      "how to view library book details",
      "how to view website book detail",
      "how to view website book details",
      "book detail viewing guidance",
      "book details viewing guidance",
      "library book detail viewing guidance",
      "library book details viewing guidance",
      "website book detail viewing guidance",
      "website book details viewing guidance"
    ],
    [
      "search book",
      "search books",
      "search library book",
      "search library books",
      "search website book",
      "search website books",
      "how to search book",
      "how to search books",
      "how to search library book",
      "how to search library books",
      "how to search website book",
      "how to search website books",
      "book searching guidance",
      "books searching guidance",
      "library book searching guidance",
      "library books searching guidance",
      "website book searching guidance",
      "website books searching guidance"
    ],
    [
      "view laptop",
      "view laptops",
      "view library laptop",
      "view library laptops",
      "view website laptop",
      "view website laptops",
      "how to view laptop",
      "how to view laptops",
      "how to view library laptop",
      "how to view library laptops",
      "how to view website laptop",
      "how to view website laptops",
      "laptop viewing guidance",
      "laptops viewing guidance",
      "library laptop viewing guidance",
      "library laptops viewing guidance",
      "website laptop viewing guidance",
      "website laptops viewing guidance"
    ],
    [
      "borrow book",
      "borrow books",
      "borrow library book",
      "borrow library books",
      "borrow website book",
      "borrow website books",
      "how to borrow book",
      "how to borrow books",
      "how to borrow library book",
      "how to borrow library books",
      "how to borrow website book",
      "how to borrow website books",
      "book borrowing guidance",
      "books borrowing guidance",
      "library book borrowing guidance",
      "library books borrowing guidance",
      "website book borrowing guidance",
      "website books borrowing guidance"
    ],
    [
      "borrow laptop",
      "borrow laptops",
      "borrow library laptop",
      "borrow library laptops",
      "borrow website laptop",
      "borrow website laptops",
      "how to borrow laptop",
      "how to borrow laptops",
      "how to borrow library laptop",
      "how to borrow library laptops",
      "how to borrow website laptop",
      "how to borrow website laptops",
      "laptop borrowing guidance",
      "laptops borrowing guidance",
      "library laptop borrowing guidance",
      "library laptops borrowing guidance",
      "website laptop borrowing guidance",
      "website laptops borrowing guidance"
    ],
    [
      "borrow study room",
      "borrow study rooms",
      "borrow library study room",
      "borrow library study rooms",
      "borrow website study room",
      "borrow website study rooms",
      "how to borrow study room",
      "how to borrow study rooms",
      "how to borrow library study room",
      "how to borrow library study rooms",
      "how to borrow website study room",
      "how to borrow website study rooms",
      "study room borrowing guidance",
      "study rooms borrowing guidance",
      "library study room borrowing guidance",
      "library study rooms borrowing guidance",
      "website study room borrowing guidance",
      "website study rooms borrowing guidance"
    ],
    [
      "print book",
      "print books",
      "print library book",
      "print library books",
      "print website book",
      "print website books",
      "how to print book",
      "how to print books",
      "how to print library book",
      "how to print library books",
      "how to print website book",
      "how to print website books",
      "book printing guidance",
      "books printing guidance",
      "library book printing guidance",
      "library books printing guidance",
      "website book printing guidance",
      "website books printing guidance"
    ],
    [
      "update info",
      "update personal info",
      "update account info",
      "update information",
      "update personal information",
      "update account information"
    ],
    [
      "task guidance",
      "tasks guidance",
      "user task guidance",
      "user tasks guidance",
      "view task guidance",
      "view tasks guidance",
      "view user task guidance",
      "view user tasks guidance",
      "how to view task guidance",
      "how to view tasks guidance",
      "how to view user task guidance",
      "how to view user tasks guidance"
    ],
    [
      "view book borrowing records",
      "view book borrowing record",
      "how to view book borrowing records",
      "how to view book borrowing record",
      "view details for book borrowing records",
      "view details for book borrowing record",
      "how to view details for book borrowing records",
      "how to view details for book borrowing record",
      "extend book borrowing records",
      "extend book borrowing record",
      "how to extend book borrowing records",
      "how to extend book borrowing record",
      "cancel book borrowing records",
      "cancel book borrowing record",
      "how to cancel book borrowing records",
      "how to cancel book borrowing record"
    ],
    [
      "view laptop borrowing records",
      "view laptop borrowing record",
      "how to view laptop borrowing records",
      "how to view laptop borrowing record",
      "view details for laptop borrowing records",
      "view details for laptop borrowing record",
      "how to view details for laptop borrowing records",
      "how to view details for laptop borrowing record",
      "cancel laptop borrowing records",
      "cancel laptop borrowing record",
      "how to cancel laptop borrowing records",
      "how to cancel laptop borrowing record"
    ],
    [
      "view room borrowing records",
      "view room borrowing record",
      "how to view room borrowing records",
      "how to view room borrowing record",
      "view details for room borrowing records",
      "view details for room borrowing record",
      "how to view details for room borrowing records",
      "how to view details for room borrowing record",
      "extend room borrowing records",
      "extend room borrowing record",
      "how to extend room borrowing records",
      "how to extend room borrowing record",
      "cancel room borrowing records",
      "cancel room borrowing record",
      "how to cancel room borrowing records",
      "how to cancel room borrowing record"
    ],
    [
      "view book printing records",
      "view book printing record",
      "how to view book printing records",
      "how to view book printing record",
      "view details for book printing records",
      "view details for book printing record",
      "how to view details for book printing records",
      "how to view details for book printing record",
      "cancel book printing records",
      "cancel book printing record",
      "how to cancel book printing records",
      "how to cancel book printing record"
    ]
  ]
  
  // Possible responses, in corresponding order
  
  const replies = [
    ["Hello!", "Hi!", "Hey!", "Hi there!","Howdy"],
    [
      "Fine... how are you?",
      "Pretty well, how are you?",
      "Fantastic, how are you?"
    ],
    [
      "Nothing much",
      "About to go to sleep",
      "Can you guess?",
      "I don't know actually"
    ],
    ["I am infinite"],
    ["I am just a bot", "I am a bot. What are you?"],
    ["The one true God, JavaScript"],
    ["I am nameless", "I don't have a name"],
    ["I love you too", "Me too"],
    ["Have you ever felt bad?", "Glad to hear it"],
    ["Why?", "Why? You shouldn't!", "Try watching TV"],
    ["What about?", "Once upon a time..."],
    ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
    ["Bye", "Goodbye", "See you later"],
    ["Sushi", "Pizza"],
    ["Bro!"],
    ["Great question"],
    ["That's ok","I understand","What do you want to talk about?"],
    ["Please say something :("],
    ["Haha!","Good one!"],
    ["Business", "Computers & Tech", "History", "Cooking", "Biographies"],
    [
      "How to win friends and influence people",
      "Think and Grow Rich",
      "Start with Why",
      "The 7 Habits of Highly Effective People",
      "HTML & CSS: Design and Build Web Sites",
      "Learning Web Design",
      "The Soul of a New Machine",
      "Learning PHP, MySQL, JavaScript, CSS and HTML5",
      "Guns, Germs, and Steel",
      "A People's History of the United States",
      "The History of the Ancient World",
      "Devil in the White City",
      "Salt, Fat, Acid, Heat",
      "On Food and Cooking",
      "Kitchen Confidential",
      "Mastering the Art of French Cooking",
      "Becoming",
      "Into the Wild",
      "Steve Jobs",
      "Unbroken"
    ],
    [
      "Dell G3 3590 Core i5-9300H (N5I5518W)",
      "Dell Vostro 3401 Core i3-1005G1 70233744",
      "Asus Vivobook A512FA-EJ099T Blue",
      "Asus Vivobook A415EP-EB118T Core i7-1165G7",
      "HP 14s-dq1100TU Core I3-1005G1 (193U0PA - Silver)",
      "HP 15s-fq1106TU Core I3-1005G1 (193Q2PA - Silver)",
      "MSI Modern 14 B11MO-010VN Core i7-1165G7",
      "MSI Modern 14 B11M-073VN Core i7-1165G7",
      "Acer Aspire 3 AS A315-54-34U1 Core i3-10110U",
      "Acer Aspire 5 A514-52-54L3 Core i5-8265U"
    ],
    [
      "Library Room 101 - Capacity 1",
      "Library Room 102 - Capacity 1",
      "Library Room 103 - Capacity 2",
      "Library Room 104 - Capacity 2",
      "Library Room 105 - Capacity 4",
      "Library Room 301 - Capacity 1",
      "Library Room 302 - Capacity 1",
      "Library Room 303 - Capacity 2",
      "Library Room 304 - Capacity 2",
      "Library Room 305 - Capacity 4"
    ],
    [
      "Library Room 101 - Capacity 1",
      "Library Room 102 - Capacity 1",
      "Library Room 103 - Capacity 2",
      "Library Room 104 - Capacity 2",
      "Library Room 105 - Capacity 4",
      "Library Room 201 - Capacity 1",
      "Library Room 202 - Capacity 1",
      "Library Room 203 - Capacity 2",
      "Library Room 204 - Capacity 2",
      "Library Room 205 - Capacity 4",
      "Library Room 301 - Capacity 1",
      "Library Room 302 - Capacity 1",
      "Library Room 303 - Capacity 2",
      "Library Room 304 - Capacity 2",
      "Library Room 305 - Capacity 4"
    ],
    [
      "Library Room 301 - Capacity 1",
      "Library Room 302 - Capacity 1",
      "Library Room 303 - Capacity 2",
      "Library Room 304 - Capacity 2",
      "Library Room 305 - Capacity 4"
    ],
    [
      "Go to the homepage and choose 'View Books' to view the current books on the library website"
    ],
    [
      "Go to the homepage and choose 'View Books' then click on link 'View Book Details' for viewing the specific book details"
    ],
    [
      "Go to the homepage and choose 'View Books' then enter the specific book or author name in the searching input field and click on button 'Search Book' for searching the needed books"
    ],
    [
      "Go to the homepage and choose 'View Laptops' to view the current laptops on the library website"
    ],
    [
      "Go to the homepage and choose 'Borrow Books', enter the needed information in the borrowing form then click on button 'Borrow Book' for borrowing the needed book"
    ],
    [
      "Go to the homepage and choose 'Borrow Laptops', enter the needed information in the borrowing form then click on button 'Borrow Laptop' for borrowing the needed laptop"
    ],
    [
      "Go to the homepage and choose 'Rent Study Room', enter the needed information in the borrowing form then click on button 'Borrow Study Room' for borrowing the needed study room"
    ],
    [
      "Go to the homepage and choose 'Print Documents', enter the needed information in the printing form then click on button 'Print Book' for reserving the needed book printing document or click on button 'Make Payment' for making printing payment"
    ],
    [
      "Go to the homepage and choose 'Update Info', enter the needed information in the updating form then click on button 'Update student/teacher/outsider information' for updating personal account information"
    ],
    [
      "Go to the homepage and choose 'About Us' for viewing guidance for executing the student or teacher or outsider tasks on the library website"
    ],
    [
      "Go to the homepage and choose 'View Book Borrowing Records' then view the current book borrowing records. After that, you can choose to whether view details or extend or cancel the current book borrowing records"
    ],
    [
      "Go to the homepage and choose 'View Laptop Borrowing Records' then view the current laptop borrowing records. After that, you can choose to whether view details or cancel the current laptop borrowing records"
    ],
    [
      "Go to the homepage and choose 'View Room Borrowing Records' then view the current room borrowing records. After that, you can choose to whether view details or extend or cancel the current room borrowing records"
    ],
    [
      "Go to the homepage and choose 'View Book Printing Records' then view the current book printing records. After that, you can choose to whether view details or cancel the current book printing records"
    ],
  ]
  
  // Random for any other user input
  
  const alternative = [
    "Same",
    "Go on...",
    "Bro...",
    "Try again",
    "I'm listening...",
    "I don't understand :/"
  ]
  
  // Whatever else you want :)
  
  const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]